cookie:
  expiry_days: 2
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    mayonaka:
      name: mayonaka
      password: $2b$12$sx5nbsZbyXTXkwB3cpHszuXW3PDnoR5GeDtcEke8k.15UMEliGcFG
preauthorized:
  emails:
  - melsby@gmail.com
