cookie:
  expiry_days: 10
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    test1:
      name: mayonaka
      password: $2b$12$ZkhkR3QVUGJIYcNe9V2K5encDx2wVuvkDQBuBHxhAfVzLOCQ1RZpS
    test2:
      name: test2
      password: $2b$12$ZkhkR3QVUGJIYcNe9V2K5encDx2wVuvkDQBuBHxhAfVzLOCQ1RZpS
    aoneko906:
      name: aoneko096
      password: $2b$12$pNJeX89FgjywkrTSBN5POuYb9.io7Zi61Y0DAw4CxlbHoj9Gj4LGS
    ヘルメス:
      name: ヘルメス
      password: $2b$12$AYUIfUXy8AQGUUdTnuT.bu.i5PDhsagsgWdodZ2DBSvaRQ6BH4Vdy
    クルエ:
      name: クルエ
      password: $2b$12$lg4AiKpGuzMTf1y1L0pu1up9V1MYM2mNU96DJpmJBYOv8gUsxnaPa
preauthorized:
  emails:
  - melsby@gmail.com
