cookie:
  expiry_days: 10
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    mayonaka:
      name: mayonaka
      password: $2b$12$9WMI1dsQUkE90nARHOkIJujvPjfr2T95jL6IWtpSZo0ZLSdVvn/5G
preauthorized:
  emails:
  - melsby@gmail.com
