cookie:
  expiry_days: 10
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    mayonaka:
      name: mayonaka
      password: $2b$12$ZkhkR3QVUGJIYcNe9V2K5encDx2wVuvkDQBuBHxhAfVzLOCQ1RZpS
    test1:
      email: test@exm.com
      name: test1
      password: $2b$12$bKMJZwJgzIR1H5MVrixtIOGnBVRqBFfZqJglurEwGBrsJRq2wb8du
preauthorized:
  emails:
  - melsby@gmail.com
