cookie:
  expiry_days: 2
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    mayonaka:
      name: mayonaka
      password: $2b$12$1FF.ZaeJe1xTJs/SfMIc.OA0zX6WeCDZC6Lp5c9SzLaWtNYuyZaeq
preauthorized:
  emails:
  - melsby@gmail.com
