cookie:
  expiry_days: 10
  key: some_signature_keys
  name: some_cookie_name
credentials:
  usernames:
    mayonaka:
      name: mayonaka
      password: $2b$12$0x7F24lTvySVXtlUENgb/ezfcJq7rqxny4F74e3cna3wCE/C49mRm
    siina:
      name: siina
      password: $2b$12$0x7F24lTvySVXtlUENgb/ezfcJq7rqxny4F74e3cna3wCE/C49mRm
    rin:
      name: rin
      password: $2b$12$0x7F24lTvySVXtlUENgb/ezfcJq7rqxny4F74e3cna3wCE/C49mRm
    hermes: 
      name: hermes
      password: $2b$12$0x7F24lTvySVXtlUENgb/ezfcJq7rqxny4F74e3cna3wCE/C49mRm
    hebi:
      name: hebi
      password: $2b$12$0x7F24lTvySVXtlUENgb/ezfcJq7rqxny4F74e3cna3wCE/C49mRm
    aizena3:
      name: aizena3
      password: $2b$12$0x7F24lTvySVXtlUENgb/ezfcJq7rqxny4F74e3cna3wCE/C49mRm
preauthorized:
  emails:
  - melsby@gmail.com
